services:
  apache:
    container_name: "grapheditor-apache-dev"
    build:
      context: .
      dockerfile: apache/Dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: "grapheditor-apache-dev"
    network_mode: host
    volumes:
      - './apache/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf'
      - './apache/httpd.conf:/usr/local/apache2/conf/httpd.conf'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: "grapheditor-frontend-dev"
    container_name: "grapheditor-frontend-dev"
    network_mode: host
    volumes:
      - './frontend:/opt/grapheditor-frontend'
      - '/opt/grapheditor-frontend/node_modules'

  backend:
    image: "grapheditor-backend-dev"
    build:
      context: .
      dockerfile: backend/Dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    network_mode: host
    restart: on-failure
    container_name: "grapheditor-backend-dev"
    volumes:
      - './backend:/opt/grapheditor-backend'
    env_file: ./.env

  neo4j-enterprise:
    image: "${DOCKER_REGISTRY}neo4j:5.26.5-enterprise" # change this to use a different version
    container_name: "neo4j-enterprise"
    ports:
      - "${NEO4J_BOLT_LISTEN_ADDRESS}:7687"
      - "${NEO4J_HTTP_LISTEN_ADDRESS}:7474"
      - "${NEO4J_HTTPS_LISTEN_ADDRESS}:6477"
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes # For development purposes
      - NEO4J_dbms_security_procedures_whitelist=gds.*, apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=gds.*, apoc.*
      - NEO4J_AUTH=${GUI_USER}/${GUI_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_trigger_enabled=true
      - NEO4J_apoc_trigger_refresh=10000

      - NEO4J_PLUGINS=["apoc", "apoc-extended", "graph-data-science"]
      - NEO4J_server_memory_heap_initial__size=1g
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache_size=2g
      - NEO4J_dbms_usage__report_enabled=false
    volumes:
      - './neo4j/data:/var/lib/neo4j/data'
      - './neo4j/plugins:/var/lib/neo4j/plugins'
