services:
  frontend-base:
    extends:
      file: docker-compose.base.yml
      service: frontend

  apache:
    extends:
      file: docker-compose.base.yml
      service: apache
    container_name: "grapheditor-apache-dev"
    build:
      context: .
      dockerfile: apache/Dockerfile.base
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: "grapheditor-apache-dev"
    network_mode: host
    volumes:
      - './apache/conf/extra/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf'
      - './apache/httpd.conf:/usr/local/apache2/conf/httpd.conf'

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        DOCKER_REGISTRY: ${DOCKER_REGISTRY}
    image: "grapheditor-frontend-dev"
    container_name: "grapheditor-frontend-dev"
    network_mode: host
    volumes:
      - './frontend:/opt/grapheditor-frontend'
      - '/opt/grapheditor-frontend/node_modules'

  backend:
    image: "grapheditor-backend-dev"
    extends:
      file: docker-compose.base.yml
      service: backend
    container_name: "grapheditor-backend-dev"
    volumes:
      - './backend:/opt/grapheditor-backend'
    env_file: ./.env

  neo4j-enterprise:
    extends:
      file: docker-compose.base.yml
      service: neo4j-enterprise
    environment:
      - NEO4J_PLUGINS=["apoc", "apoc-extended", "graph-data-science"]
      - NEO4J_server_memory_heap_initial__size=1g
      - NEO4J_server_memory_heap_max__size=2g
      - NEO4J_server_memory_pagecache_size=2g
    volumes:
      - './neo4j/data:/var/lib/neo4j/data'
      - './neo4j/plugins:/var/lib/neo4j/plugins'
